### ISSUE TITLE
Read db files fail if there are in a folder.

### ISSUE THREAD

**Issue by CodingCarlos** [CampusMadridProjects/directory-backend#4]
It fails by reading the file, but I think the real problem is it cannot wite the file with a name containing `/` characters.

Would be a good idea to enable, as we have for file names, a constant to update the containing folder.

**Comment by musikame** [comment]
@CodingCarlos in case this is related to the Cloudstorage bucket and db json files I can move to the root folder - let me know?

**Comment by CodingCarlos** [comment]
Yes, that's the thing.

Move the files to root folder would be a workaround to avoid the issue, but
the bug would still being there.

The fix is easy, so I think that fix it it's better than work in the edge
cases ;)

Thx!

El 6 ago. 2018 10:08, "Edu Duque" <notifications@github.com> escribió:

@CodingCarlos <https://github.com/CodingCarlos> in case this is related to
the Cloudstorage bucket and db json files I can move to the root folder -
let me know?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CampusMadridProjects/directory-backend/issues/4#issuecomment-410624007>,
or mute the thread

**Comment by musikame** [comment]
Sounds good, in case a temp workaround helps to unlock this let me know so we can update the spreadsheet script to upload to the root folder-
Gcs!

**Comment by CodingCarlos** [comment]
Pull request launched! #5

**Comment by musikame** [comment]
Let me know if you need help with the json upload from the spreadsheet (you have rights to perform the push)
